// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: framework_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FrameWork_FW int32

const (
	FrameWork_RUBY_ON_RAILS FrameWork_FW = 0
	FrameWork_SYMPHONY      FrameWork_FW = 1
	FrameWork_ANGULAR_JS    FrameWork_FW = 2
	FrameWork_REACT_JS      FrameWork_FW = 3
	FrameWork_CAKE          FrameWork_FW = 4
	FrameWork_NODE          FrameWork_FW = 5
	FrameWork_YII           FrameWork_FW = 6
	FrameWork_LARAVEL       FrameWork_FW = 7
	FrameWork_MAGENTO       FrameWork_FW = 8
	FrameWork_SPRING        FrameWork_FW = 9
	FrameWork_DRUPAL        FrameWork_FW = 10
)

// Enum value maps for FrameWork_FW.
var (
	FrameWork_FW_name = map[int32]string{
		0:  "RUBY_ON_RAILS",
		1:  "SYMPHONY",
		2:  "ANGULAR_JS",
		3:  "REACT_JS",
		4:  "CAKE",
		5:  "NODE",
		6:  "YII",
		7:  "LARAVEL",
		8:  "MAGENTO",
		9:  "SPRING",
		10: "DRUPAL",
	}
	FrameWork_FW_value = map[string]int32{
		"RUBY_ON_RAILS": 0,
		"SYMPHONY":      1,
		"ANGULAR_JS":    2,
		"REACT_JS":      3,
		"CAKE":          4,
		"NODE":          5,
		"YII":           6,
		"LARAVEL":       7,
		"MAGENTO":       8,
		"SPRING":        9,
		"DRUPAL":        10,
	}
)

func (x FrameWork_FW) Enum() *FrameWork_FW {
	p := new(FrameWork_FW)
	*p = x
	return p
}

func (x FrameWork_FW) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameWork_FW) Descriptor() protoreflect.EnumDescriptor {
	return file_framework_message_proto_enumTypes[0].Descriptor()
}

func (FrameWork_FW) Type() protoreflect.EnumType {
	return &file_framework_message_proto_enumTypes[0]
}

func (x FrameWork_FW) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameWork_FW.Descriptor instead.
func (FrameWork_FW) EnumDescriptor() ([]byte, []int) {
	return file_framework_message_proto_rawDescGZIP(), []int{0, 0}
}

type FrameWork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Framwork FrameWork_FW `protobuf:"varint,1,opt,name=framwork,proto3,enum=awesome.project.FrameWork_FW" json:"framwork,omitempty"`
	Level    float32      `protobuf:"fixed32,2,opt,name=level,proto3" json:"level,omitempty"`
	Years    int32        `protobuf:"varint,3,opt,name=years,proto3" json:"years,omitempty"`
}

func (x *FrameWork) Reset() {
	*x = FrameWork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framework_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameWork) ProtoMessage() {}

func (x *FrameWork) ProtoReflect() protoreflect.Message {
	mi := &file_framework_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameWork.ProtoReflect.Descriptor instead.
func (*FrameWork) Descriptor() ([]byte, []int) {
	return file_framework_message_proto_rawDescGZIP(), []int{0}
}

func (x *FrameWork) GetFramwork() FrameWork_FW {
	if x != nil {
		return x.Framwork
	}
	return FrameWork_RUBY_ON_RAILS
}

func (x *FrameWork) GetLevel() float32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *FrameWork) GetYears() int32 {
	if x != nil {
		return x.Years
	}
	return 0
}

var File_framework_message_proto protoreflect.FileDescriptor

var file_framework_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x77, 0x65, 0x73, 0x6f,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x87, 0x02, 0x0a, 0x09, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x39, 0x0a, 0x08, 0x66, 0x72, 0x61, 0x6d,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x77, 0x65,
	0x73, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x2e, 0x46, 0x57, 0x52, 0x08, 0x66, 0x72, 0x61, 0x6d, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x79, 0x65, 0x61,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x22,
	0x92, 0x01, 0x0a, 0x02, 0x46, 0x57, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x55, 0x42, 0x59, 0x5f, 0x4f,
	0x4e, 0x5f, 0x52, 0x41, 0x49, 0x4c, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x59, 0x4d,
	0x50, 0x48, 0x4f, 0x4e, 0x59, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x4e, 0x47, 0x55, 0x4c,
	0x41, 0x52, 0x5f, 0x4a, 0x53, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x41, 0x43, 0x54,
	0x5f, 0x4a, 0x53, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x4b, 0x45, 0x10, 0x04, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x59, 0x49, 0x49,
	0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x41, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x10, 0x07, 0x12,
	0x0b, 0x0a, 0x07, 0x4d, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x4f, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x50, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x09, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x52, 0x55, 0x50,
	0x41, 0x4c, 0x10, 0x0a, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_framework_message_proto_rawDescOnce sync.Once
	file_framework_message_proto_rawDescData = file_framework_message_proto_rawDesc
)

func file_framework_message_proto_rawDescGZIP() []byte {
	file_framework_message_proto_rawDescOnce.Do(func() {
		file_framework_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_framework_message_proto_rawDescData)
	})
	return file_framework_message_proto_rawDescData
}

var file_framework_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_framework_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_framework_message_proto_goTypes = []interface{}{
	(FrameWork_FW)(0), // 0: awesome.project.FrameWork.FW
	(*FrameWork)(nil), // 1: awesome.project.FrameWork
}
var file_framework_message_proto_depIdxs = []int32{
	0, // 0: awesome.project.FrameWork.framwork:type_name -> awesome.project.FrameWork.FW
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_framework_message_proto_init() }
func file_framework_message_proto_init() {
	if File_framework_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_framework_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameWork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_framework_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_framework_message_proto_goTypes,
		DependencyIndexes: file_framework_message_proto_depIdxs,
		EnumInfos:         file_framework_message_proto_enumTypes,
		MessageInfos:      file_framework_message_proto_msgTypes,
	}.Build()
	File_framework_message_proto = out.File
	file_framework_message_proto_rawDesc = nil
	file_framework_message_proto_goTypes = nil
	file_framework_message_proto_depIdxs = nil
}
