// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: language_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Language_Lang int32

const (
	Language_PHP         Language_Lang = 0
	Language_JAVA        Language_Lang = 1
	Language_GO          Language_Lang = 2
	Language_PYTHON      Language_Lang = 3
	Language_RUBY        Language_Lang = 4
	Language_JAVASCRIPT  Language_Lang = 5
	Language_C_PLUS_PLUS Language_Lang = 6
	Language_SCALA       Language_Lang = 7
	Language_SWIFT       Language_Lang = 8
)

// Enum value maps for Language_Lang.
var (
	Language_Lang_name = map[int32]string{
		0: "PHP",
		1: "JAVA",
		2: "GO",
		3: "PYTHON",
		4: "RUBY",
		5: "JAVASCRIPT",
		6: "C_PLUS_PLUS",
		7: "SCALA",
		8: "SWIFT",
	}
	Language_Lang_value = map[string]int32{
		"PHP":         0,
		"JAVA":        1,
		"GO":          2,
		"PYTHON":      3,
		"RUBY":        4,
		"JAVASCRIPT":  5,
		"C_PLUS_PLUS": 6,
		"SCALA":       7,
		"SWIFT":       8,
	}
)

func (x Language_Lang) Enum() *Language_Lang {
	p := new(Language_Lang)
	*p = x
	return p
}

func (x Language_Lang) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language_Lang) Descriptor() protoreflect.EnumDescriptor {
	return file_language_message_proto_enumTypes[0].Descriptor()
}

func (Language_Lang) Type() protoreflect.EnumType {
	return &file_language_message_proto_enumTypes[0]
}

func (x Language_Lang) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language_Lang.Descriptor instead.
func (Language_Lang) EnumDescriptor() ([]byte, []int) {
	return file_language_message_proto_rawDescGZIP(), []int{0, 0}
}

type Language struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language Language_Lang `protobuf:"varint,1,opt,name=language,proto3,enum=awesome.project.Language_Lang" json:"language,omitempty"`
	Level    float32       `protobuf:"fixed32,2,opt,name=level,proto3" json:"level,omitempty"`
	Years    int32         `protobuf:"varint,3,opt,name=years,proto3" json:"years,omitempty"`
}

func (x *Language) Reset() {
	*x = Language{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_language_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_language_message_proto_rawDescGZIP(), []int{0}
}

func (x *Language) GetLanguage() Language_Lang {
	if x != nil {
		return x.Language
	}
	return Language_PHP
}

func (x *Language) GetLevel() float32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Language) GetYears() int32 {
	if x != nil {
		return x.Years
	}
	return 0
}

var File_language_message_proto protoreflect.FileDescriptor

var file_language_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x77, 0x65, 0x73, 0x6f, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x22, 0xe2, 0x01, 0x0a, 0x08, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x61, 0x77, 0x65, 0x73, 0x6f,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x79, 0x65, 0x61, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x22, 0x6e,
	0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x48, 0x50, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4a, 0x41, 0x56, 0x41, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x4f, 0x10,
	0x02, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x59, 0x54, 0x48, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x08, 0x0a,
	0x04, 0x52, 0x55, 0x42, 0x59, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x4a, 0x41, 0x56, 0x41, 0x53,
	0x43, 0x52, 0x49, 0x50, 0x54, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x5f, 0x50, 0x4c, 0x55,
	0x53, 0x5f, 0x50, 0x4c, 0x55, 0x53, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x43, 0x41, 0x4c,
	0x41, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x57, 0x49, 0x46, 0x54, 0x10, 0x08, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_language_message_proto_rawDescOnce sync.Once
	file_language_message_proto_rawDescData = file_language_message_proto_rawDesc
)

func file_language_message_proto_rawDescGZIP() []byte {
	file_language_message_proto_rawDescOnce.Do(func() {
		file_language_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_language_message_proto_rawDescData)
	})
	return file_language_message_proto_rawDescData
}

var file_language_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_language_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_language_message_proto_goTypes = []interface{}{
	(Language_Lang)(0), // 0: awesome.project.Language.Lang
	(*Language)(nil),   // 1: awesome.project.Language
}
var file_language_message_proto_depIdxs = []int32{
	0, // 0: awesome.project.Language.language:type_name -> awesome.project.Language.Lang
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_language_message_proto_init() }
func file_language_message_proto_init() {
	if File_language_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_language_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Language); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_language_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_language_message_proto_goTypes,
		DependencyIndexes: file_language_message_proto_depIdxs,
		EnumInfos:         file_language_message_proto_enumTypes,
		MessageInfos:      file_language_message_proto_msgTypes,
	}.Build()
	File_language_message_proto = out.File
	file_language_message_proto_rawDesc = nil
	file_language_message_proto_goTypes = nil
	file_language_message_proto_depIdxs = nil
}
